version: '3.7'

services:
  php:
    build:
      context: ../
      dockerfile: devops/Docker/php/Dockerfile
    restart: always
    volumes:
      - ../:/project
    env_file:
      - ../.env

  client:
    build:
      context: ../
      dockerfile: devops/Docker/react/Dockerfile
    command: npm start
    volumes:
      - ../front/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - php
    env_file:
      - ../.env

  nginx:
    depends_on:
      - php
    image: nginx:latest
    ports:
      - "8008:80"
    restart: always
    volumes:
      - ../:/project
      - ./default.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - ../.env
