export const types = {
    // Sync
    SHOW_RESULT: "SHOW_RESULT",
    SET_PLAYER_SIGN: 'SET_PLAYER_SIGN',
    NEXT_MOVE: 'NEXT_MOVE',
    RESET_CAPTION: 'RESET_CAPTION',
    SHOW_ERROR: 'SHOW_ERROR',
};
