export const types = {
    // Sync
    MAKE_MOVE: "MAKE_MOVE",
    FILL_BOARD: "FILL_BOARD",
    RESET_BOARD: "RESET_BOARD",
    GAME_OVER: "GAME_OVER",

    // Async
    MAKE_MOVE_ASYNC: "MAKE_MOVE_ASYNC",
    CHOOSE_SIGN_ASYNC: "CHOOSE_SIGN_ASYNC",
    GET_STATE_ASYNC: "GET_STATE_ASYNC",
    RESET_BOARD_ASYNC: "RESET_BOARD_ASYNC",
};
